export const dict = {
  fr: {
    app_title: 'Persona 2 IS - Image Lab',
    tab_home: 'Accueil',
    tab_lab: 'Laboratoire',
    tab_queue: "File d'attente / ISO",
    logs_title: "Journal d'événements",
    logs_empty: 'Aucune action récente.',
    logs_clear: 'Effacer le journal',
    browse: 'Parcourir',
    
    // Project Init / Home
    home_title: 'Bienvenue dans P2IS Image Lab',
    home_desc: 'Cet outil vous permet d\'explorer, extraire et modifier les textures et images contenues dans les fichiers .BIN du jeu Persona 2: Innocent Sin (PSP).',
    project_config: 'Configuration du projet',
    iso_label: 'Fichier ISO Original (.iso)',
    workspace_label: 'Dossier de travail (Workspace)',
    init_btn: 'Initialiser le projet',
    init_running: 'Extraction en cours...',
    
    workflow_title: 'Guide d\'utilisation',
    workflow_step1: 'Sélectionnez votre ISO et votre dossier de travail sur cet écran.',
    workflow_step2: 'Parcourez et visualisez les images dans l\'onglet "Laboratoire".',
    workflow_step3: 'Exportez au format PNG et éditez les textures sans modifier leurs dimensions.',
    workflow_step4: 'Injectez les textures modifiées dans la file d\'attente.',
    workflow_step5: 'Appliquez les modifications et générez votre nouvel ISO dans l\'onglet "File d\'attente".',
    
    formats_title: 'Formats GIM supportés',
    fmt_index4_title: 'INDEX4 (4 bits)',
    fmt_index4_desc: 'Palette de 16 couleurs. Utilisé pour les icônes, polices et petits éléments d\'interface.',
    fmt_index8_title: 'INDEX8 (8 bits)',
    fmt_index8_desc: 'Palette de 256 couleurs. Utilisé pour les portraits, décors et menus principaux.',
    fmt_rgba_title: 'RGBA (16/32 bits)',
    fmt_rgba_desc: 'Couleurs vraies avec canal alpha.',
    fmt_swz_title: 'SWZ (Swizzled)',
    fmt_swz_desc: 'Organisation mémoire entrelacée optimisée pour le processeur graphique de la PSP.',
    warning_resolution: 'Attention : Conservez scrupuleusement la résolution originale (largeur x hauteur) des images lors de l\'édition pour éviter tout plantage du jeu.',

    // Image Lab
    lab_source_dir: 'Dossier CPK extrait (Source)',
    lab_export_dir: 'Dossier d\'exportation',
    lab_scan_btn: 'Scanner',
    lab_scanning: 'Analyse...',
    lab_files_found: 'fichiers d\'images trouvés',
    lab_no_files: 'Aucun fichier .BIN / .BNP trouvé.',
    lab_select_file: 'Sélectionnez un fichier dans la liste pour voir les textures.',
    lab_extract_png: 'Exporter PNG',
    lab_extract_gim: 'Exporter GIM',
    lab_inject_mod: 'Injecter Mod',
    lab_preview: 'Aperçu',
    
    // Build Queue
    queue_title: 'File d\'attente des modifications',
    queue_empty: 'Aucune image en attente d\'injection.',
    queue_empty_desc: 'Modifiez une image dans le Laboratoire et cliquez sur "Injecter Mod".',
    queue_iso_section: 'Génération de l\'ISO patché',
    queue_iso_desc: 'L\'outil va compiler le nouveau CPK et mettre à jour l\'ISO originale tout en préservant la structure du disque.',
    queue_clear: 'Vider',
    queue_apply: 'Appliquer les injections',
    queue_applying: 'Encodage...',
    queue_rebuild_iso: 'Construire l\'ISO',
    queue_rebuilding_iso: 'Création de l\'ISO...',
    queue_note: 'Note : Les injections remplacent directement les textures dans le dossier extrait avant la création de l\'ISO.'
  },
  en: {
    app_title: 'Persona 2 IS - Image Lab',
    tab_home: 'Home',
    tab_lab: 'Image Lab',
    tab_queue: 'Queue / ISO Build',
    logs_title: 'Event Logs',
    logs_empty: 'No recent actions.',
    logs_clear: 'Clear logs',
    browse: 'Browse',
    
    // Project Init / Home
    home_title: 'Welcome to P2IS Image Lab',
    home_desc: 'This tool allows you to explore, extract, and modify textures and images contained in the .BIN files of Persona 2: Innocent Sin (PSP).',
    project_config: 'Project Configuration',
    iso_label: 'Original ISO File (.iso)',
    workspace_label: 'Working Folder (Workspace)',
    init_btn: 'Initialize Project',
    init_running: 'Extracting...',
    
    workflow_title: 'User Guide',
    workflow_step1: 'Select your ISO and working directory on this screen.',
    workflow_step2: 'Browse and preview images in the "Image Lab" tab.',
    workflow_step3: 'Export to PNG format and edit textures without changing their dimensions.',
    workflow_step4: 'Inject modified textures into the queue.',
    workflow_step5: 'Apply changes and build your new ISO in the "Queue / ISO Build" tab.',
    
    formats_title: 'Supported GIM Formats',
    fmt_index4_title: 'INDEX4 (4-bit)',
    fmt_index4_desc: '16-color palette. Used for icons, fonts, and small UI elements.',
    fmt_index8_title: 'INDEX8 (8-bit)',
    fmt_index8_desc: '256-color palette. Used for portraits, backgrounds, and main menus.',
    fmt_rgba_title: 'RGBA (16/32-bit)',
    fmt_rgba_desc: 'True color format with alpha channel.',
    fmt_swz_title: 'SWZ (Swizzled)',
    fmt_swz_desc: 'Interleaved memory layout optimized for the PSP graphic chip.',
    warning_resolution: 'Warning: Always maintain the exact original resolution (width x height) when editing images to prevent game crashes.',

    // Image Lab
    lab_source_dir: 'Extracted CPK Folder (Source)',
    lab_export_dir: 'Export Folder',
    lab_scan_btn: 'Scan',
    lab_scanning: 'Scanning...',
    lab_files_found: 'image files found',
    lab_no_files: 'No .BIN / .BNP files found.',
    lab_select_file: 'Select a file from the list to view contained textures.',
    lab_extract_png: 'Export PNG',
    lab_extract_gim: 'Export GIM',
    lab_inject_mod: 'Inject Mod',
    lab_preview: 'Preview',
    
    // Build Queue
    queue_title: 'Modification Queue',
    queue_empty: 'No images waiting in queue.',
    queue_empty_desc: 'Modify an image in the Image Lab and click "Inject Mod".',
    queue_iso_section: 'Patched ISO Generation',
    queue_iso_desc: 'The tool compiles the new CPK and updates the original ISO while preserving disc layout.',
    queue_clear: 'Clear',
    queue_apply: 'Apply Injections',
    queue_applying: 'Encoding...',
    queue_rebuild_iso: 'Build ISO',
    queue_rebuilding_iso: 'Building ISO...',
    queue_note: 'Note: Injections update textures directly inside the extracted workspace before building the ISO.'
  }
};
